services:
  - type: web
    name: GoVibe
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn prever_perfil:app"
    pythonVersion: 3.10
